//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace touchvg.core {

public class MgCmdCompass : MgCmdArc3P {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal MgCmdCompass(global::System.IntPtr cPtr, bool cMemoryOwn) : base(touchvgPINVOKE.MgCmdCompass_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MgCmdCompass obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MgCmdCompass() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          touchvgPINVOKE.delete_MgCmdCompass(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public MgCmdCompass(string name) : this(touchvgPINVOKE.new_MgCmdCompass__SWIG_0(name), true) {
  }

  public MgCmdCompass() : this(touchvgPINVOKE.new_MgCmdCompass__SWIG_1(), true) {
  }

  public override void release() {
    touchvgPINVOKE.MgCmdCompass_release(swigCPtr);
  }

  public override bool initialize(MgMotion sender, MgStorage s) {
    bool ret = touchvgPINVOKE.MgCmdCompass_initialize(swigCPtr, MgMotion.getCPtr(sender), MgStorage.getCPtr(s));
    return ret;
  }

  public override bool draw(MgMotion sender, GiGraphics gs) {
    bool ret = touchvgPINVOKE.MgCmdCompass_draw(swigCPtr, MgMotion.getCPtr(sender), GiGraphics.getCPtr(gs));
    return ret;
  }

  public override bool click(MgMotion sender) {
    bool ret = touchvgPINVOKE.MgCmdCompass_click(swigCPtr, MgMotion.getCPtr(sender));
    return ret;
  }

}

}
