//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace touchvg.core {

public class MgCmdSector : MgCmdArcCSE {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal MgCmdSector(global::System.IntPtr cPtr, bool cMemoryOwn) : base(touchvgPINVOKE.MgCmdSector_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MgCmdSector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MgCmdSector() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          touchvgPINVOKE.delete_MgCmdSector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public MgCmdSector(string name) : this(touchvgPINVOKE.new_MgCmdSector__SWIG_0(name), true) {
  }

  public MgCmdSector() : this(touchvgPINVOKE.new_MgCmdSector__SWIG_1(), true) {
  }

  public override bool initialize(MgMotion sender, MgStorage s) {
    bool ret = touchvgPINVOKE.MgCmdSector_initialize(swigCPtr, MgMotion.getCPtr(sender), MgStorage.getCPtr(s));
    return ret;
  }

}

}
